services:
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            -   "3000:3000"
        environment:
            - NODE_ENV=production
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            -   "8080:8080"
        environment:
            - ROD_BROWSER_PATH=/usr/bin/chromium
        volumes:
            -   rod-cache:/root/.cache/rod/browser
    database:
        image: postgres
        container_name: postgres_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: stock_data
        ports:
            -   "5432:5432"
        volumes:
            -   postgres_storage:/var/lib/postgresql/data
volumes:
    rod-cache:
    postgres_storage: